name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build & Publish Electron app
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          npx electron-builder --win --x64 --arm64
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          npx electron-builder --mac --x64 --arm64
        else
          npx electron-builder --linux --x64 --arm64
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
